
<div class="container">
    <h2><i class="fas fa-cogs"></i>  Panneau d'Edition</h2>
    
    <form action="add_post.php" method="post">

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="author">Auteur</label>
            </div>
            <select class="custom-select" name="author" id="author">
                <?php foreach($result_author as $author){
                        echo '<option value="' . $author['id'] . '" >' . $author['first_name'] . ' ' . $author['last_name'] . '</option>';
                }

               ?>
            </select>
        </div>

        <div class="form-group">
            <label for="title">Titre du post</label>
            <input class="form-control form-control-lg" type="text" id="title"  maxlength="100" name="title" required>
            <label for="content">Contenu du post</label>
            <textarea class="form-control" id="content" name="content" rows="3" maxlength="10000" required></textarea>
            <input type="submit" class="btn btn-primary btn-lg" value="Enregistrer">
            
            <a href="admin.php"><button type="button" class="btn btn-secondary btn-lg">Annuler</button></a>
        </div>
    </form>
</div>
