  
<form action="admin_conectionform.php" class="hide" id="formulaire_admin" method="post">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">User / Mail</span>
        </div>
        <input type="text" class="form-control" name="user" placeholder="Username ou Email" aria-label="Username" aria-describedby="basic-addon1">
        <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Password</span>
        </div>
        <input type="password" class="form-control" name="password" placeholder="Password" aria-label="Username" >
        <input type="submit" value="envoyer">
    </div>
</form>