<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Shojumaru&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-10"><h1><a href="index.php"><i class="fas fa-microphone-alt"></i>Encore un blog ?! #nonmaisallo</a></h1></div>
                <div class="col-2">
                    <?php if(isset($_SESSION['connected']) && $_SESSION['connected']==true){
                        echo '<p><div><a class="bt" href="admin.php?page=admin">Administration</a></div></p>';
                        echo '<p><div><a class="bt" href="admin.php?deco=deco">deconnection</a></div></p>';
                    }else{ 
                        echo '<p><div id="bouton_admin" ><a class="bt" href="#">Connection</a></div></p>';
                        echo '<p><div><a class="bt" href="index.php?page=inscription">inscription</a></div></p>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </header>

    <section id="core">
        
        <?php 
        if(isset($_GET['page']) == 'inscription'){
            include 'create_user.phtml';
        }else{
            include 'show_post.php'; 
        }?>
    </section>
        



<!-- BOOTSTRAP -->
    <script src="js/main.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" defer></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</body>
</html>