<div class="container">
    <h2><i class="fas fa-home"></i>Accueil</h2>
    
    <?php foreach($result as $post):?>
        
        <div class="jumbotron" id="post<?= $post['id'] ?>">
            <h3 class="display-4"><?= $post['title'] ?></h3>
            <p class="lead">Article écrit par : <?= $post['first_name'] ?> <?= $post['last_name'] ?> le <?= $post['date']  ?></p>
        <hr class="my-4">
        <?php if(isset($_GET['post']) && $post['id'] == $_GET['post']){

            echo '<p class="content">' . $post['post_content'] . '</p>';
        }else{
            echo '<p class="content">' . substr($post['post_content'], 0, 15) . '[...]</p>';
            echo '<p class="lead">
                <a class="btn btn-primary btn-lg" href="index.php?post=' . $post['id'] . '#post' . $post['id'] . '" role="button">Lire la suite</a>
            </p>';
        }
        ?>
            
        </div>
    <?php endforeach;?>
    
</div>



